version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nestjs:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - DOCKER_IMAGE_NAME=mehdibs1920/tp-docker-nestjs
    image: mehdibs1920/tp-docker-nestjs
    container_name: coffee-1
    ports:
      - "3000:3002"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
